# Generated by Django 5.0 on 2024-04-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
